/*
# Create transactional_logs, provider_settings, domain_auth_records, test_email_records

1. New Tables
- `transactional_logs` — transactional emails generated by connected systems.
- `provider_settings` — email delivery provider configuration. API keys kept in edge function secrets.
- `domain_auth_records` — SPF, DKIM, DMARC domain authentication records and statuses.
- `test_email_records` — sandbox/test email sends, clearly identified as tests.

2. Security
- RLS enabled on all. All policies gated by admin_profiles, scoped TO authenticated.
*/

CREATE TABLE IF NOT EXISTS public.transactional_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_email text NOT NULL,
  email_type text NOT NULL DEFAULT 'system_notification',
  subject text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  provider_message_id text,
  error_details text,
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_at timestamptz,
  clicked_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tl_recipient_idx ON public.transactional_logs (recipient_email);
CREATE INDEX IF NOT EXISTS tl_status_idx ON public.transactional_logs (status);
CREATE INDEX IF NOT EXISTS tl_email_type_idx ON public.transactional_logs (email_type);
CREATE INDEX IF NOT EXISTS tl_created_at_idx ON public.transactional_logs (created_at);

ALTER TABLE public.transactional_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_tl" ON public.transactional_logs;
CREATE POLICY "admin_select_tl" ON public.transactional_logs
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_insert_tl" ON public.transactional_logs;
CREATE POLICY "admin_insert_tl" ON public.transactional_logs
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_update_tl" ON public.transactional_logs;
CREATE POLICY "admin_update_tl" ON public.transactional_logs
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_delete_tl" ON public.transactional_logs;
CREATE POLICY "admin_delete_tl" ON public.transactional_logs
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

CREATE TRIGGER set_updated_at_transactional_logs
  BEFORE UPDATE ON public.transactional_logs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.provider_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_name text NOT NULL DEFAULT 'resend',
  is_active boolean DEFAULT true,
  is_connected boolean DEFAULT false,
  sender_name text DEFAULT '',
  sender_email text DEFAULT '',
  reply_to_email text DEFAULT '',
  connect_id text DEFAULT '',
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS provider_name_unique ON public.provider_settings (provider_name);

ALTER TABLE public.provider_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_ps" ON public.provider_settings;
CREATE POLICY "admin_select_ps" ON public.provider_settings
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_insert_ps" ON public.provider_settings;
CREATE POLICY "admin_insert_ps" ON public.provider_settings
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_update_ps" ON public.provider_settings;
CREATE POLICY "admin_update_ps" ON public.provider_settings
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_delete_ps" ON public.provider_settings;
CREATE POLICY "admin_delete_ps" ON public.provider_settings
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

CREATE TRIGGER set_updated_at_provider_settings
  BEFORE UPDATE ON public.provider_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.domain_auth_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain text NOT NULL,
  record_type text NOT NULL,
  host text DEFAULT '',
  required_value text DEFAULT '',
  verification_status text NOT NULL DEFAULT 'not_configured',
  last_checked_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dar_domain_idx ON public.domain_auth_records (domain);
CREATE INDEX IF NOT EXISTS dar_status_idx ON public.domain_auth_records (verification_status);

ALTER TABLE public.domain_auth_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_dar" ON public.domain_auth_records;
CREATE POLICY "admin_select_dar" ON public.domain_auth_records
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_insert_dar" ON public.domain_auth_records;
CREATE POLICY "admin_insert_dar" ON public.domain_auth_records
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_update_dar" ON public.domain_auth_records;
CREATE POLICY "admin_update_dar" ON public.domain_auth_records
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_delete_dar" ON public.domain_auth_records;
CREATE POLICY "admin_delete_dar" ON public.domain_auth_records
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

CREATE TRIGGER set_updated_at_domain_auth_records
  BEFORE UPDATE ON public.domain_auth_records
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.test_email_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  test_recipient_email text NOT NULL,
  template_id uuid REFERENCES public.email_templates(id) ON DELETE SET NULL,
  campaign_id uuid REFERENCES public.campaigns(id) ON DELETE SET NULL,
  subject text DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  result text DEFAULT '',
  error_info text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ter_created_at_idx ON public.test_email_records (created_at);

ALTER TABLE public.test_email_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_ter" ON public.test_email_records;
CREATE POLICY "admin_select_ter" ON public.test_email_records
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_insert_ter" ON public.test_email_records;
CREATE POLICY "admin_insert_ter" ON public.test_email_records
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_update_ter" ON public.test_email_records;
CREATE POLICY "admin_update_ter" ON public.test_email_records
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

DROP POLICY IF EXISTS "admin_delete_ter" ON public.test_email_records;
CREATE POLICY "admin_delete_ter" ON public.test_email_records
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.admin_profiles ap WHERE ap.user_id = auth.uid()));

CREATE TRIGGER set_updated_at_test_email_records
  BEFORE UPDATE ON public.test_email_records
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
